2018-02-03 18:46:38,180 ERROR: Exception on /addproduct [POST] 
 		 [in e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\default.py", line 667, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1676, in process
    value = _strict_as_bool(value)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1653, in _strict_as_bool
    "Not a boolean value: %r" % value)
TypeError: Not a boolean value: 'true'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\codeutsavaproj\ecommerce_flask\app\routes.py", line 157, in add_product
    db_instance.session.commit()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 937, in commit
    self.transaction.commit()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 461, in commit
    self._prepare_impl()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 441, in _prepare_impl
    self.session.flush()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 2237, in flush
    self._flush(objects)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 2363, in _flush
    transaction.rollback(_capture_exception=True)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\session.py", line 2327, in _flush
    flush_context.execute()
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\orm\persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 1132, in _execute_context
    None, None)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\engine\default.py", line 667, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1676, in process
    value = _strict_as_bool(value)
  File "e:\codeutsavaproj\ecommerce_flask\pehla_virtualenv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1653, in _strict_as_bool
    "Not a boolean value: %r" % value)
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'true' [SQL: 'INSERT INTO product (name, category, mrp, offer_price, cod_eligible, seller_id, details, delivery_cost, returnable, availability, rating, imagepath) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'imagepath': 'jygvjy', 'category': '1', 'cod_eligible': 'true', 'details': 'kuk', 'mrp': '7', 'availability': '55', 'offer_price': '89', 'name': 'jygy', 'delivery_cost': '56', 'returnable': 'true', 'rating': None, 'seller_id': None}]]
2018-02-03 18:48:55,754 INFO: Microblog startup 
 		 [in E:\codeutsavaproj\ecommerce_flask\app\__init__.py:49]
